name: Export puml to svg

on:
  push:
    paths:
      - 'puml/*.puml'

env:
  PLANTUML_JAR: https://downloads.sourceforge.net/project/plantuml/plantuml.jar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: openjdk

    - name: Download plantuml.jar
      run: |
        wget "$PLANTUML_JAR" -O plantuml.jar

    - name: Export puml to svg
      run: |
        mkdir -p puml/svg
        for file in puml/*.puml; do
          filename="${file%.*}"
          java -jar plantuml.jar -tsvg "$file" -o "puml/svg/${filename##*/}.svg"
        done

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Export puml to svg [skip ci]"
        push: true
